# Generated by Django 6.0.1 on 2026-01-15 04:14

from django.db import migrations 


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('expenses', 'Category')

    default_categories = [
        "Food",
        "Travel",
        "Shopping",
        "Rent",
        "Bills",
        "Entertainment",
        "Health",
        "Other",
    ]
    for name in default_categories:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_category_options'),
    ]

    operations = [
         migrations.RunPython(create_default_categories),
    ]
